### ISSUE TITLE
Option do to FR for all subs simultanously?

### ISSUE THREAD

**Issue by andreifoldes** [ViCCo-Group/frrsa#36]
Greetings,

It is my understanding in the paper that FRRSA is being done on a subject level (each subject gets its own weight-vector), however I was wondering whether it could be tweaked to find an optimal weight given a set of participant datasets thus finding an optimal group-level weight vector to a model?

Would reweighting e.g.:  fmri voxel data to the group average voxel data  (as per Fig3c) and then running FRRSA on the (subject level reweighted fmri voxel data, model RSM) achieve this in a roundabout way?

**Comment by PhilippKaniuth** [comment]
> It is my understanding in the paper that FRRSA is being done on a subject level (each subject gets its own weight-vector)

It depends. When reweighting individual units of a computational model, then the weights vector for the model units was estimated separately for each subject RSM. When reweighting brain measurement channels, then yes, each participant's brain measurements were independently reweighted to predict e.g. a model's RSM.

> however I was wondering whether it could be tweaked to find an optimal weight given a set of participant datasets thus finding an optimal group-level weight vector to a model?

In the first case described above, you could average participants' (fMRI) RSMs. That way, you would reweight model units to optimally predict a group-averaged (fMRI) RSM. In the second case, though, you cannot simply average participants'  brain measurements (I think mapping voxels between participants is very hard - I am not an expert on this but it's out of scope for `frrsa`). 

> Would reweighting e.g.: fmri voxel data to the group average voxel data (as per Fig3c) and then running FRRSA on the (subject level reweighted fmri voxel data, model RSM) achieve this in a roundabout way?

I understand that you thought about the following:
1. Reweight every participant's fMRI voxels to best predict the group average voxel RSM.
2. Use the resulting weights to somehow individually adjust participants' fMRI voxel activity?
3. Run `frrsa` on those changed fMRI voxels (separately for every participant?) to predict some target.

If so, I would advise against this. Note that, strictly speaking, `frrsa` reweights the _(dis-)similarity_ of the `predictor` (e.g. of every unit or voxel) to best predict the `target` RDM / RSM, not the _raw activity_ within the predictor's channels itself! Therefore, step 1 cannot be used to kind of make each participant's raw voxel activity more similar to some group average, only to make each participant's fMRI RSM more similar to the group average RSM. I think there is no valid way to align _raw_ voxel activity beween participants in the context of FR-RSA.

Overall, if I understood you correctly, I think your best bet with `frrsa` is to average RSMs / RDMs from different participants and use that average matrix as the `target`.
